.gitignore
README.md
requirements.txt
setup.py

Upgraded requirements.txt
Modified README.md to reference pip install instead of manual install
Ticket: CFE-3266
Changelog: Title

Added setup.py script to enable installation from pip

---

cf_remote/web.py

We don't want multiple threads to download the same package in
parallel and, most of all, we want to prevent on thread from
using a package that is still being downloaded by a different
thread.
Ticket: CFE-3496
Changelog: Parallel installation now properly downloads missing packages

Prevent issues when multiple threads download the same package

---

README.md
cf_remote/__init__.py
cf_remote/__main__.py
cf_remote/demo.py
cf_remote/paths.py
cf_remote/ssh.py
cf_remote/utils.py
cf_remote/version.py
setup.py

save_file: Fixed issue causing attempt to create directory with empty name

---

cf_remote/remote.py

Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

CFE-3681 Fix: do not fail when using SSH/paramiko connections

---

cf_remote/commands.py
cf_remote/spawn.py

Needs a new field called 'token' in the config file, or
environment variables should be set.

Add support for AWS temporary secrets

---

cf_remote/packages.py
cf_remote/remote.py

So that we can reuse the code in other places.
Ticket: ENT-6147

Separate code for selecting package for a given host

---

cf_remote/commands.py
cf_remote/main.py
requirements.txt

Added a command to show spawned hosts

---

cf_remote/main.py

https://tracker.mender.io/browse/CFE-3929

Fixed help output for cf-remote save

---

.github/workflows/python-tests.yml
.gitignore
cf_remote/main.py
cf_remote/packages.py
cf_remote/utils.py
tests/test_cache.py

https://tracker.mender.io/browse/CFE-3928

Added help output when no arguments are given

---

setup.py

Same as:
https://github.com/cfengine/cfbs/pull/104

Fixed local install version numbers

---

cf_remote/spawn.py

In case the cloud driver doesn't provide info about an instance
we spawned, the instance should just report values indicating
missing data instead of raising an exception and potentially
killing everything.
Ticket: CFE-3922
Changelog: Missing instance info in cloud driver no longer causes a traceback

Handle missing instance info in driver gracefully

---

test/test_example.py

We have tests in tests/ directory.

Removed test/ directory

---

cf_remote/aramid.py
cf_remote/cloud_data.py
cf_remote/commands.py
cf_remote/main.py
cf_remote/packages.py
cf_remote/remote.py
cf_remote/spawn.py
cf_remote/ssh.py
cf_remote/utils.py

```
$ cf-remote info -H centos-6-x64 | grep "OS"
OS            : CentOS 6
$ cf-remote info -H centos-7-x64 | grep "OS"
OS            : CentOS 7
$ cf-remote info -H debian-10-x64 | grep "OS"
OS            : Debian 10
$ cf-remote info -H debian-11-x64 | grep "OS"
OS            : Debian 11
$ cf-remote info -H debian-5-x32 | grep "OS"
OS            : Linux
$ cf-remote info -H debian-5-x64 | grep "OS"
OS            : Linux
$ cf-remote info -H debian-6-x32 | grep "OS"
OS            : Linux
$ cf-remote info -H debian-6-x64 | grep "OS"
OS            : Linux
$ cf-remote info -H debian-7-x32 | grep "OS"
OS            : Debian 7
$ cf-remote info -H debian-7-x64 | grep "OS"
OS            : Debian 7
$ cf-remote info -H debian-8-x64 | grep "OS"
OS            : Debian 8
$ cf-remote info -H debian-9-x64 …
```

CFE-3946: cf-remote now show same OS name as MP

---

cf_remote/ssh.py
tests/test_ssh.py

CFE-4024: Fix running commands on localhost instead of using ssh

---

cf_remote/ssh.py

With aramid cf-remote is running the good old 'ssh' utility to
run commands on remote hosts. While being very reliable and
supporting standard things like SSH agent, standard config
files,... this approach has a downside of being slow because each
command executed on a remote host creates a new SSH connection.
This change improves the behavior by using so-called Control
Master processes (see man:ssh_config(5)) which basically allow
reuse of a single SSH connection for multiple commands.
We could move this code to aramid itself, but our Connection
class matches the concept of a persistent connection very well so
it's a better fit, at least for now.
Ticket: CFE-4002
Changelog: Make cf-remote faster by reusing SSH connections to hosts

Use an SSH control master process to speed things up

---

cf_remote/packages.py
cf_remote/remote.py

CFE-4078: Added zypper install method and opensuse-leap knowledge about packages

---

.github/workflows/python-publish.yml

When trying to make a new release, I saw a new error message from git describe about nothing to describe. So I'm hoping this blind fix can help.

GH Action: Ensure all tags are fetched

---

cf_remote/cloud_data.py

Ticket: ENT-11139
Changelog: Title

ENT-11139: Added ami info for Red Hat 9

---

.github/workflows/python-tests.yml

Added simple sanity check if cf-remote will run on various versions of python

---

cf_remote/commands.py
cf_remote/spawn.py

ENT-11134: improve the error message format

---

cf_remote/cloud_data.py

Use 'centos' as the user on CentOS machines

---

cf_remote/commands.py
cf_remote/main.py
cf_remote/remote.py

Supercedes: https://github.com/cfengine/cf-remote/pull/101

ENT-12386: Added uninstall --purge option to remove "everything"

---

cf_remote/remote.py

Fixed error handling in deploy

---

cf_remote/cloud_data.py

Removed debian-9 from spawnable platforms

---

cf_remote/remote.py
cf_remote/utils.py
nt-discovery.sh
setup.py
tests/test_utils.py

Created nt-discovery.sh file
