README.md
`/usr/local/bin` usually requires elevated privileges to modify.
```
> $ ls -al /usr/local/bin/. | head -n 2
total 44812
drwxr-xr-x  3 root root     4096 Jan 26 13:47 .
```
=> Prefixed manual symlink with sudo

cf_remote/commands.py, cf_remote/main.py, cf_remote/remote.py, cf_remote/ssh.py, cf_remote/utils.py
Enabled a few different ways to use this command.
Inside masterfiles folder:
```
cf-remote deploy --hub hub .
```
Relative path with trailing slash:
```
cf-remote deploy --hub hub ../masterfiles/
```
Tarball directly, without running autotools and tar:
```
cf-remote deploy --hub hub /home/olehermanse/.cfengine/cf-remote/masterfiles.tgz
```
Gzipped tarball from URL:
```
cf-remote deploy --hub hub https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.15.3/misc/cfengine-masterfiles-3.15.3-1.pkg.tar.gz
```
Installed masterfiles folder, without autogen or configure:
```
cf-remote deploy --hub hub /var/cfengine/masterfiles
```
=> Made deploy command more friendly and accept tarballs, URLs, relative paths, etc.

.github/workflows/python-publish.yml
Previously, creating a draft release and publishing it, would not trigger this action.
Docs are a little hard to decipher, but it seems to me that what we want is "published":
https://docs.github.com/en/rest/reference/repos#releases
=> Fix GitHub Action event trigger for releases

cf_remote/remote.py
This was broken in e61ed477e4. The install_package() function
needs to be called with the downloaded package, not its URL.
Ticket: CFE-3869
=> Fix --remote-download to install the downloaded package

cf_remote/commands.py, cf_remote/main.py
Getting Ansible inventory based on the information about spawned
VMs can be very useful for testing various Ansible-related
features.
Ticket: ENT-6147
Changelog: Added --ansible-inventory option to 'cf-remote spawn'
=> Add --ansible-inventory to 'cf-remote spawn'

cf_remote/commands.py, cf_remote/main.py
No support for private IPs (yet).
Looks like this:
```
$ cf-remote save -H root@198.211.105.11,root@128.199.44.119 --role hub --name hubs
$ cf-remote info -H hubs
root@198.211.105.11
OS            : ubuntu (debian)
CFEngine      : 3.18.1 (Enterprise)
Policy server : 198.211.105.11
Binaries      : dpkg, apt
root@128.199.44.119
OS            : ubuntu (debian)
CFEngine      : 3.18.1 (Enterprise)
Policy server : 128.199.44.119
Binaries      : dpkg, apt
$ cf-remote destroy --all
Destroying all hosts
Deleting saved group '@hubs' without terminating VMs:
hubs-1: root@198.211.105.11 (hub)
hubs-2: root@128.199.44.119 (hub)
```
=> Added save command for adding hosts spawned elsewhere

cf_remote/commands.py, cf_remote/main.py
Example:
```
$ cf-remote deploy
Found saved/spawned hubs: ubuntu@54.154.69.41
Found cfbs policy set: 'out/masterfiles.tgz'
Deploying to:
ubuntu@54.154.69.41
OS            : ubuntu (debian)
CFEngine      : 3.18.1 (Enterprise)
Policy server : None
Binaries      : dpkg, apt
Copying: 'out/masterfiles.tgz' to 'ubuntu@54.154.69.41'
Renaming 'masterfiles.tgz' -> 'masterfiles.tgz' on 'ubuntu@54.154.69.41'
Running: 'rm -rf /var/cfengine/masterfiles.delete && mv /var/cfengine/masterfiles /var/cfengine/masterfiles.delete && mv masterfiles /var/cfengine/masterfiles && rm -rf /var/cfengine/masterfiles.delete && cf-agent -Kf update.cf && cf-agent -K'
```
Ticket: https://tracker.mender.io/browse/CFE-3930
=> deploy command now uses spawned / saved hubs and cfbs policy set by default

cf_remote/commands.py
Only require the credentials for the particular cloud provider if
destroying machines spawned in the clouds.
Ticket: CFE-3935
Changelog: Destroying saved hosts now works even without cloud credentials
=> Don't fail with no cloud creds if destroying saved hosts only

requirements.txt
It's not imported and used anywhere in the code since
05ddc5287b5d.
=> Remove tabulate from requirements.txt

cf_remote/aramid.py, cf_remote/ssh.py, requirements.txt, setup.py
Minimal changes required. They make things take longer because *aramid* doesn't do any SSH connection caching, but now things actually work reliably and don't require Python 3.7+.
=> Use aramid instead of fabric+paramiko

cf_remote/ssh.py
scp and cf-remote default to transferring files to the home folder,
where you end up if you ssh to the machine. aramid defaults to
using the same path as in src, which might not exist or be accessible.
Restored the previous behavior by explicitly giving destination
path to aramid library.
=> Fixed broken file transfer introduced by aramid

.github/workflows/python-package.yml, cf_remote/commands.py, cf_remote/main.py, cf_remote/remote.py, cf_remote/ssh.py, cf_remote/utils.py, setup.py, test/test_example.py
For cfbs to be python 3.5 compatible, its dependency cf-remote must also
be python 3.5 compatible.
Ticket: CFE-3792
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
=> CFE-3792: Changed python version requirement from >=3.6 to >=3.5

cf_remote/aramid.py
Newer SSH clients try disabling ssh-rsa by default.
ssh-rsa is still used, notably by the CentOS 6 machines in AWS.
Since we support CentOS 6 and want cf-remote to "just work",
we will enable this by default. People should still / independently
of this ensure they are not using SHA-1, and also that they switch
away from ssh-rsa on their SSH servers.
=> Added options for allowing ssh-rsa by default

cf_remote/cloud_data.py
Apparently the CoreOS AMI does not exist.
```
$  cf-remote spawn --platform coreos --name coreos --count 1 --role client
Spawning VMs...Traceback (most recent call last):
File "/usr/local/bin/cf-remote", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/site-packages/cf_remote/main.py", line 399, in main
exit_code = run_command_with_args(args.command, args)
File "/usr/local/lib/python3.10/site-packages/cf_remote/main.py", line 196, in run_command_with_args
return commands.spawn(args.platform, args.count, args.role, args.name,
File "/usr/local/lib/python3.10/site-packages/cf_remote/commands.py", line 335, in spawn
vms = spawn_vms(requests, creds, region, key_pair,
File "/usr/local/lib/python3.10/site-packages/cf_remote/spawn.py", line 369, in spawn_vms
vm = …
```
=> Remove non-existent AMI

cf_remote/ssh.py
Fixed some earlier here: a77369aedb52a6869fe45b6cda3195e5ef8f2839 but missed a few.
The underlying issue is that aramid result.stdout and stderr
are strings but when we connect to localhost we use a subprocess
and result.stdout/stderr are byte sequences and so can't be appended
to each other as strings can.
Ticket: CFE-4024
=> CFE-4024: Fixed print/debug messages when running commands on localhost

cf_remote/remote.py
In some cases the arm64/aarch64 package might be selected instead.
Ticket: CFE-4049
=> Fixed package selection for x86_64/amd64

.github/workflows/python-tests.yml
AFAICT when ubuntu-latest starts to become ubuntu 22, Python 3.5 and 3.6 will fail.
=> GitHub Actions: Specified Ubuntu 20 explicitly

cf_remote/remote.py
Fixed bug where installing packages containing spaces and parenthesis in
the filename would result in a syntax error in the remote shell.
=> CFE-4150: Fixed bug when installing packages containing spaces

cf_remote/packages.py, tests/test_packages.py
We have specific packages for all of these Ubuntu and Debian choices,
so it's better if we don't suggest the "wrong" package.
=> Stopped suggesting debian packages for ubuntu hosts

cf_remote/cloud_data.py
This should speed up `apt upgrade` on fresh box.
=> Updated the Ubuntu 22 AMI ID to the latest one used in AWS quick start

cf_remote/remote.py
This change makes cf-remote install Red Hat packages on Rocky and Alma Linux as
they are both derivatives of Red Hat.
Ticket: ENT-10479
Changelog: Title
=> ENT-10479: Added support for installing Red Hat packages on Rocky and Alma Linux

.gitignore, cf_remote/cloud_data.py
```
larsewi@zyra:cf-remote % cf-remote spawn --platform debian-12-x64 --count 1 --role hub --name test
---snip---
larsewi@zyra:cf-remote % cf-remote show
@test: (1 host in eu-west-1, aws)
admin@54.72.6.161
hub, latest-debian-12-x64hub0, debian-12-x64, m3.xlarge, 172.31.25.167, 
54.72.6.161, 59d02ac536cea38915173a2295601f9d4b8107ba, larsewi-ed25519, 
cfengine-test
Total: 1 host in 1 group
larsewi@zyra:cf-remote % ssh admin@54.72.6.161
---snip---
admin@ip-172-31-25-167:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
admin@ip-172-31-25-167:~$ 
logout …
```
=> ENT-10347: Added Debian 12 x86_64 AMI to cf-remote

cf_remote/cloud_data.py
```
$ cf-remote spawn --platform suse-15-x64 --count 1 --role client --name suse-15
Spawning VMs....DONE
Waiting for VMs to get IP addresses....DONE
Details about the spawned VMs can be found in /Users/larsewi/.cfengine/cf-remote/cloud_state.json
$ cf-remote spawn --platform suse-12-x64 --count 1 --role client --name suse-12
Spawning VMs....DONE
Waiting for VMs to get IP addresses....DONE
Details about the spawned VMs can be found in /Users/larsewi/.cfengine/cf-remote/cloud_state.json
$ cf-remote show
@suse-15: (1 host in eu-west-1, aws)
ec2-user@52.50.182.71
client, lasuse-15-suse-15-x64client0, suse-15-x64, t2.xlarge, 
172.31.41.148, 52.50.182.71, 63b7362ac1e27cae0b32014aa18644ed07198c69, 
larsewi-ed25519, cfengine-test
@suse-12: (1 host in eu-west-1, aws)
ec2-user@3.253.61.16
client, …
```
=> cloud_data.py: Added SUSE 15 & 12 AMI's

cf_remote/remote.py
- remote.py: Formatted with black
- Removed the --allow-unsigned-rpm when installing on SUSE 12
=> Fixed cf-remote install package for SUSE 12-SP5

cf_remote/commands.py
=> ENT-11158: cf-remote deploy now looks for masterfiles in current working directory

cf_remote/commands.py, cf_remote/spawn.py
New invalid credentials error message: 
Ticket: ENT-11134
=> ENT-11134: proper message when invalid cloud credentials

cf_remote/spawn.py
List of available platforms is printed when user inputs unknown platform
Ticket: ENT-11138
=> ENT-11138: proper error message when typing unsupported/unknown platform

README.md, cf_remote/cloud_data.py, cf_remote/commands.py, cf_remote/spawn.py, tests/aws-spawn-test.sh, tests/test_spawn.py
Before we hard-coded AMI and had to update them fairly often and add them when we supported a new platform.
Here we change to querying for AMI based on known trusted owner IDs.
This should make it so that new platforms are automatically available and any updates will be in-place automatically as well.
Ticket: CFE-4322
=> CFE-4322: Changed cf-remote spawn with AWS to query for AMI from known owners

cf_remote/remote.py
sudo is already used / needed for other parts of cf-remote
(such as cf-remote install and deploy), so attempting to use it
here should be acceptable.
Ticket: CFE-4361
=> CFE-4361: Fixed issue where policy server IP was not printed in info command

cf_remote/packages.py
On Fedora 40 cf-remote was selecting the SUSE 15 package instead of the EL9 package.
Ticket: ENT-11766
Changelog: Title
=> ENT-11766: Fixed package selected on Fedora 40

.github/workflows/python-tests.yml, cf_remote/cloud_data.py
fourth point is the cause
Ticket: CFE-4407
=> CFE-4407: added ubuntu-24 name pattern for aws image criteria

cf_remote/remote.py
When installing, you can see that CFE is not installed:
Then we bootstrap and see that CFE is installed, but not bootstrapped yet
CFE installed and bootstrapped:
=> Added helpful message about "not bootstrapped yet"

cf_remote/remote.py
=> Fixed file extension error when installing package

cf_remote/remote.py, cf_remote/ssh.py
This restores the previous behavior (output-wise) from before nt-discovery
was introduced.
=> cf-remote: Made nt-discovery parts quiet by default

cf_remote/ssh.py
cf-remote is currently failing local install due to the recent changes in 0.6.0.
=> Fixed issue with unrecognized keyword argument 'hide'

cf_remote/cloud_data.py
=> Added aws alpine platform Had to specify t3 instead of t2 as alpine images require EUFI which are available in t3.

.github/actions/set-up-legacy-python/action.yml, .github/workflows/black-format.yml, .github/workflows/black.yml, .github/workflows/python-publish.yml, .github/workflows/tests.yml
Ubuntu 20.04 runner is being deprecated.
=> Bump runner Ubuntu version, while handling legacy Python versions

cf_remote/log.py, tests/test_cache.py
Since the value is never assigned to, only read from, the global
statements make no difference here.
Newer versions of flake8 complain about this.
=> Removed unneeded global statements

cf_remote/nt-discovery.sh, cf_remote/remote.py
Hub before change:
```bash
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (master)$ python3 cf_remote info -H hubbefore
ubuntu@54.229.152.35
OS            : Ubuntu 20
CFEngine      : 3.24.1 (Enterprise)
Policy server : None (not bootstrapped yet)
Binaries      : dpkg, apt
```
Hub after change:
```bash
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (role-info)$ python3 cf_remote info -H hubbefore
ubuntu@54.229.152.35
OS            : Ubuntu 20
CFEngine      : 3.24.1 (Enterprise hub)
Policy server : None (not bootstrapped yet)
Binaries      : dpkg, apt
```
Client before change:
```bash
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (master)$ python3 cf_remote info -H clientbefore
ubuntu@52.31.25.14
OS            : …
```
=> CFE-3919: Added role in cf-remote info

cf_remote/nt-discovery.sh, cf_remote/remote.py
cf-remote info before change:
```bash
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (master)$ python3 cf_remote info -H hubbefore
ubuntu@54.229.152.35
OS            : Ubuntu 20
CFEngine      : 3.24.1 (Enterprise)
Policy server : None (not bootstrapped yet)
Binaries      : dpkg, apt
```
cf-remote info after change:
```bash
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (cfengine_id)$ python3 cf_remote info -H hubbefore
ubuntu@54.229.152.35
OS            : Ubuntu 20
CFEngine      : 3.24.1 (Enterprise)
Policy server : None (not bootstrapped yet)
CFEngine ID   : SHA=478526c182bceec13f27c45aa6be6ac0bad9255c2d2a589f80fd5a9a872d4e0e
Binaries      : dpkg, apt
```
=> CFE-4518: Added CFEngine ID in cf-remote info

cf_remote/aramid.py, cf_remote/commands.py, cf_remote/remote.py, cf_remote/utils.py, cf_remote/web.py
In the ticket mentioned in this commit, cf-remote seem to never copy downloaded files to the remote host for version 3.21.4. It is actually hanging indefinitely after seeing that the checksum of the artifact doesn't match the checksum of the downloaded package. This is because under the hood, `download_package` calls `sys.exit` if the checksum doesn't match. However, using `sys.exit` inside of a pooled process causes undefined behavior. The pool hangs indefinitely, waiting for the thread to return.
Previous output:
```
(.venv) victor-moene@victomoe:~/northern.tech/cf-remote (master)$ python3 cf_remote --version 3.21.4  install --hub debz --bootstrap debz
admin@63.35.228.231
OS            : Debian 12
CFEngine      : 3.21.4 (Enterprise hub)
Policy server : …
```
=> ENT-12764 Fixed unhandled invalid checksum error when downloading packages

cf_remote/aramid.py
I am not sure how many asserts we need here, and if it is enough to only have the in the class constructors
=> CFE-4499: Added asserts in aramid classes

cf_remote/main.py
Most often I want to just spawn a single VM. Hence, I'd rather have the
`--count` argument default to `1` instead of having to specify it each
time.
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
=> Set default spawn count to 1

cf_remote/remote.py, cf_remote/ssh.py
When piping the output of the installation command (for example `sudo dpkg -i package.deb`) for newer nova hub packages, cf_remote hangs. Cfengine gets correctly installed but when cf-remote waits for its output, it never finishes. My theory is that the is something wrong with how the scripts in the package interact with stdin, stdout or the terminal, when run in non-interactive mode. I managed to fix this issue by running the installation command inside its own pty (pseudo terminal interface). 
The way I made it work is by wrapping the installation command inside `script`, which creates a pty for the process. `script -qec "command" /dev/null`. This allows cf-remote to directly pipe from the script command and it works. I don't know if this is a perfect fix, I don't know if we want to …
=> CFE-4576: Fixed blocking ssh connection for newer nova packages

cf_remote/commands.py, cf_remote/demo.py, cf_remote/remote.py, cf_remote/ssh.py
Depends on:
https://github.com/cfengine/cf-remote/pull/151
https://github.com/cfengine/cf-remote/pull/152
=> ENT-13007: Fixed admin demo user for cf-remote install --demo
